// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mircat} from '../models';

export function GetConfig():Promise<mircat.Config>;

export function SetConfig(arg1:mircat.Config):Promise<boolean>;
