// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClientTcpClose(arg1:number):Promise<void>;

export function ClientTcpCloseAll():Promise<void>;

export function ClientTcpOpen():Promise<number>;

export function ClientTcpSend(arg1:number,arg2:string):Promise<void>;
