// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClientTcpClose(arg1) {
  return window['go']['mircat']['ConnManager']['ClientTcpClose'](arg1);
}

export function ClientTcpCloseAll() {
  return window['go']['mircat']['ConnManager']['ClientTcpCloseAll']();
}

export function ClientTcpOpen() {
  return window['go']['mircat']['ConnManager']['ClientTcpOpen']();
}

export function ClientTcpSend(arg1, arg2) {
  return window['go']['mircat']['ConnManager']['ClientTcpSend'](arg1, arg2);
}
