// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClientTcpClose(arg1) {
  return window['go']['mircat']['ConnManager']['ClientTcpClose'](arg1);
}

export function ClientTcpCloseAll() {
  return window['go']['mircat']['ConnManager']['ClientTcpCloseAll']();
}

export function ClientTcpOpen() {
  return window['go']['mircat']['ConnManager']['ClientTcpOpen']();
}

export function ClientTcpSend(arg1, arg2) {
  return window['go']['mircat']['ConnManager']['ClientTcpSend'](arg1, arg2);
}

export function ServerBroadcastMessage(arg1) {
  return window['go']['mircat']['ConnManager']['ServerBroadcastMessage'](arg1);
}

export function ServerSendMessage(arg1, arg2) {
  return window['go']['mircat']['ConnManager']['ServerSendMessage'](arg1, arg2);
}

export function ServerTcpStart() {
  return window['go']['mircat']['ConnManager']['ServerTcpStart']();
}

export function ServerTcpStop() {
  return window['go']['mircat']['ConnManager']['ServerTcpStop']();
}

export function TransferBroadcastToClient(arg1) {
  return window['go']['mircat']['ConnManager']['TransferBroadcastToClient'](arg1);
}

export function TransferBroadcastToServer(arg1) {
  return window['go']['mircat']['ConnManager']['TransferBroadcastToServer'](arg1);
}

export function TransferSendToClient(arg1, arg2) {
  return window['go']['mircat']['ConnManager']['TransferSendToClient'](arg1, arg2);
}

export function TransferSendToServer(arg1, arg2) {
  return window['go']['mircat']['ConnManager']['TransferSendToServer'](arg1, arg2);
}

export function TransferTcpStart() {
  return window['go']['mircat']['ConnManager']['TransferTcpStart']();
}

export function TransferTcpStop() {
  return window['go']['mircat']['ConnManager']['TransferTcpStop']();
}
