// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClientTcpClose(arg1) {
  return window['go']['main']['App']['ClientTcpClose'](arg1);
}

export function ClientTcpCloseAll() {
  return window['go']['main']['App']['ClientTcpCloseAll']();
}

export function ClientTcpOpen() {
  return window['go']['main']['App']['ClientTcpOpen']();
}

export function ClientTcpSend(arg1, arg2) {
  return window['go']['main']['App']['ClientTcpSend'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
